'use client';
import { useState } from 'react';
export default function LoginForm({enabled}:{enabled:boolean}){
 const [email,setEmail]=useState(''),[token,setToken]=useState(''),[sent,setSent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 async function submit(event:React.FormEvent){event.preventDefault();setBusy(true);setError('');setMessage('');try{
 const r=await fetch(sent?'/api/auth/verify-code':'/api/auth/request-code',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,token})});const j=await r.json() as {error?:string};if(!r.ok)throw Error(j.error||'Sign-in failed.');
 if(sent)window.location.assign('/');else {setSent(true);setMessage('Check your inbox and spam folder for the six-digit code.');}
 }catch(e){setError(e instanceof Error?e.message:'Try again later.');}finally{setBusy(false);}}
 return <main className="login-page"><a className="brand" href="/">Save<span>Half</span></a><section className="login-card"><span className="eyebrow">YOUR FAVOURITES, SAVED</span><h1>Welcome back.</h1><p>Sign in or create an account with your email. Gmail addresses are supported. Your favourites stay with your account.</p>{!enabled?<div className="setup-notice"><strong>Email verification is awaiting setup.</strong><p>The owner needs to connect Supabase and configure email delivery. ChatGPT sign-in is available now.</p></div>:<form onSubmit={submit}><label>Email address<input type="email" autoComplete="email" required maxLength={254} value={email} disabled={sent||busy} onChange={e=>setEmail(e.target.value)} placeholder="you@gmail.com"/></label>{sent&&<label>Verification code<input inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} required value={token} onChange={e=>setToken(e.target.value.replace(/\D/g,''))} placeholder="6-digit code"/></label>}<button className="primary" disabled={busy}>{busy?'Please wait…':sent?'Verify & sign in':'Email me a code'}</button>{sent&&<button type="button" disabled={busy} onClick={()=>{setSent(false);setToken('');setMessage('');}}>Change email or request a new code</button>}</form>}{message&&<p role="status">{message}</p>}{error&&<p className="login-error" role="alert">{error}</p>}<a className="chatgpt-login" href="/signin-with-chatgpt?return_to=%2F" target="_top">Continue with ChatGPT</a><p className="small-text">Email sessions last up to one hour. We never ask for your Gmail password. ChatGPT and email accounts have separate favourite lists.</p><a href="/">← Back to products</a></section></main>;
}
