import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';
import ts from 'typescript';
const moduleFrom=async(source)=>import('data:text/javascript;base64,'+Buffer.from(ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText).toString('base64'));
const stripped=(path)=>readFileSync(path,'utf8').replace(/^import .*;\n/gm,'');
const rates=new Map();let cookie,platformUser=null;
const env={SUPABASE_URL:'https://example.supabase.co',SUPABASE_PUBLISHABLE_KEY:'test-key',DB:{prepare(){return {bind(key,window,limit){return {async run(){const previous=rates.get(key);const count=previous?.window===window?previous.count:0;if(count>=limit)return {meta:{changes:0}};rates.set(key,{window,count:count+1});return {meta:{changes:1}};}};}};}}};
globalThis.__emailAuth={env,cookies:async()=>({get:()=>cookie?{value:cookie}:undefined}),getChatGPTUser:async()=>platformUser};
const auth=await moduleFrom('const {env,cookies,getChatGPTUser}=globalThis.__emailAuth;\n'+stripped('lib/email-auth.ts'));
assert.ok(auth.authConfig());env.SUPABASE_URL='https://example.supabase.co.attacker.test';assert.equal(auth.authConfig(),null);env.SUPABASE_URL='http://example.supabase.co';assert.equal(auth.authConfig(),null);env.SUPABASE_URL='https://example.supabase.co';
assert.equal(auth.verifiedIdentity({id:'00000000-0000-0000-0000-000000000001',email:'a@gmail.com'}),null);
const identity={id:'00000000-0000-0000-0000-000000000001',email:'a@gmail.com',email_confirmed_at:'2026-10-01T00:00:00Z'};
assert.equal(auth.verifiedIdentity(identity).userId,'email:'+identity.id);
let sendFailure=false;const previousFetch=globalThis.fetch;
globalThis.fetch=async(url,options)=>{
 assert.ok(url.startsWith('https://example.supabase.co/auth/v1/'));
 if(url.endsWith('/user'))return options.headers.Authorization==='Bearer verified-token'?Response.json(identity):Response.json({error:'invalid'},{status:401});
 if(url.endsWith('/otp'))return sendFailure?Response.json({error:'SMTP unavailable'},{status:500}):Response.json({});
 if(url.endsWith('/verify'))return JSON.parse(options.body).token==='123456'?Response.json({access_token:'verified-token',expires_in:99999}):Response.json({error:'invalid OTP'},{status:401});
 return Response.json({});
};
cookie='forged-token';assert.equal(await auth.getUser(),null);cookie='verified-token';assert.equal((await auth.getUser()).userId,'email:'+identity.id);cookie=undefined;platformUser={userId:'platform-id',email:'other@example.com'};assert.equal((await auth.getUser()).userId,'platform-id');platformUser=null;
globalThis.__authRoute=auth;
const imports='const {authBody,authConfig,authReply,authRequest,allowAuth,verifySession,SESSION_COOKIE}=globalThis.__authRoute;\n';
const send=await moduleFrom(imports+stripped('app/api/auth/request-code/route.ts'));
const verify=await moduleFrom(imports+stripped('app/api/auth/verify-code/route.ts'));
const req=(body,origin='https://example.test')=>new Request('https://example.test/api/auth',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json','CF-Connecting-IP':'192.0.2.1'},body:JSON.stringify(body)});
assert.equal((await send.POST(req({email:'a@gmail.com'},'https://attacker.test'))).status,403);
assert.equal((await send.POST(req({email:'bad'}))).status,400);
assert.equal((await send.POST(req({email:'x'.repeat(2000)}))).status,413);
assert.equal((await verify.POST(req({email:'a@gmail.com',token:'<script>'}))).status,400);
assert.equal((await verify.POST(req({email:'a@gmail.com',token:'000000'}))).status,401);
const success=await verify.POST(req({email:'a@gmail.com',token:'123456'}));assert.equal(success.status,200);
assert.deepEqual(await success.json(),{ok:true});const setCookie=success.headers.get('Set-Cookie');assert.match(setCookie,/HttpOnly; Secure; SameSite=Lax/);assert.match(setCookie,/Max-Age=3600/);
assert.equal((await verify.POST(req({email:'wrong@gmail.com',token:'123456'}))).status,401);
sendFailure=true;assert.equal((await send.POST(req({email:'a@gmail.com'}))).status,502);sendFailure=false;
assert.equal((await send.POST(req({email:'a@gmail.com'}))).status,200);assert.equal((await send.POST(req({email:'a@gmail.com'}))).status,200);assert.equal((await send.POST(req({email:'a@gmail.com'}))).status,429);
delete env.SUPABASE_PUBLISHABLE_KEY;assert.equal((await send.POST(req({email:'b@gmail.com'}))).status,503);
globalThis.fetch=previousFetch;
console.log('Passed: managed identity verification, forged sessions, provider errors, OTP input/origin checks, private cookies, expiry, email mismatch and persistent throttling.');
