import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
import ts from 'typescript';
const compile=s=>ts.transpileModule(s,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;
const moduleFrom=s=>import('data:text/javascript;base64,'+Buffer.from(compile(s)).toString('base64'));
const catalogue=await moduleFrom(readFileSync('lib/catalog.ts','utf8'));
// Cloudflare's module initialization clock must not erase the seed catalogue.
const realNow=Date.now;
let startupCatalogue;
try{Date.now=()=>0;startupCatalogue=await moduleFrom(readFileSync('lib/catalog.ts','utf8')+'\n// epoch startup regression');}finally{Date.now=realNow;}
assert.equal(startupCatalogue.observedOffers.length,6);
assert.ok(startupCatalogue.observedOffers.every(d=>d&&d.id));
const catalog=catalogue.aggregateDeals(new Date('2026-10-01'));
assert.equal(catalog.deals.length,6);assert.equal(new Set(catalog.deals.map(d=>d.id)).size,6);
const valid=catalog.deals[0];
for(const invalid of [{...valid,price:-1},{...valid,price:NaN},{...valid,quantity:0},{...valid,source:'https://www.woolworths.com.au.attacker.test/shop/productdetails/321220/oats'},{...valid,source:'https://www.woolworths.com.au:443@127.0.0.1/'},{...valid,source:'https://www.woolworths.com.au/shop/productdetails/321220/oats?redirect=http://127.0.0.1/'},{...valid,source:'https://www.woolworths.com.au/apis/secret'},{...valid,source:'javascript:alert(1)'},{...valid,retailer:'Attacker'},{...valid,id:'bad<script>'},{...valid,checked:'no date'},{...valid,checked:'2099-01-01T00:00:00Z'}])assert.equal(catalogue.validateDeal(invalid),null);
assert.equal(catalogue.isFresh(valid,Date.parse(valid.checked)+7*3600000),false);
assert.equal(catalogue.isFresh(valid,Date.parse(valid.checked)+1000),true);
assert.equal(catalogue.unitPrice({...valid,price:1.5,quantity:.75}),2);
const coles=catalog.deals.find(d=>d.id==='coles-oats');assert.equal(coles.price,null);assert.equal(catalogue.isFresh(coles,Date.parse(coles.checked)),false);
const rows=[];let user=null;let offline=false;
globalThis.__savedTest={env:{DB:{prepare(sql){return {bind(...args){return {async all(){if(offline)throw Error('simulated');return {results:rows.filter(r=>r.user===args[0]).map(r=>({deal_id:r.id}))};},async run(){if(offline)throw Error('simulated');if(sql.startsWith('INSERT')){if(!rows.some(r=>r.user===args[0]&&r.id===args[1]))rows.push({user:args[0],id:args[1]});}else if(sql.startsWith('DELETE')){const i=rows.findIndex(r=>r.user===args[0]&&r.id===args[1]);if(i>=0)rows.splice(i,1);}return {};}};}};}}},getChatGPTUser:async()=>user?{userId:user}:null,loadCatalogue:async()=>catalog};
const routeSource=readFileSync('app/api/saved/route.ts','utf8').replace(/^import .*;\n/gm,'');
const routes=await moduleFrom('const {env,getChatGPTUser:getUser,loadCatalogue}=globalThis.__savedTest;\n'+routeSource);
const req=(body,origin='https://example.test',method='POST')=>new Request('https://example.test/api/saved',{method,headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify(body)});
assert.equal((await routes.GET()).status,401);assert.equal((await routes.POST(req({id:valid.id}))).status,401);
user='alice';assert.equal((await routes.POST(req({id:valid.id},'https://attacker.test'))).status,403);
assert.equal((await routes.POST(req({id:'unknown'}))).status,400);assert.equal((await routes.POST(req({id:'x'.repeat(2000)}))).status,413);
assert.equal((await routes.POST(new Request('https://example.test/api/saved',{method:'POST',headers:{Origin:'https://example.test','Content-Type':'text/plain'},body:'x'}))).status,415);
assert.equal((await routes.POST(req({id:valid.id}))).status,200);assert.equal((await routes.POST(req({id:valid.id}))).status,200);
assert.deepEqual((await (await routes.GET()).json()).ids,[valid.id]);
user='bob';assert.deepEqual((await (await routes.GET()).json()).ids,[]);assert.equal((await routes.DELETE(req({id:valid.id},'https://example.test','DELETE'))).status,200);
user='alice';assert.deepEqual((await (await routes.GET()).json()).ids,[valid.id]);assert.equal((await routes.DELETE(req({id:valid.id},'https://example.test','DELETE'))).status,200);
assert.deepEqual((await (await routes.GET()).json()).ids,[]);
offline=true;const previous=console.error;console.error=()=>{};assert.equal((await routes.GET()).status,503);console.error=previous;
globalThis.__retailerTests=catalogue;
const pages=await moduleFrom('const {safeProductUrl,validateDeal}=globalThis.__retailerTests;\n'+readFileSync('lib/retailer-pages.ts','utf8').replace(/^import .*;\n/gm,''));
const ld=(offer)=>'<script type="application/ld+json">'+JSON.stringify({'@type':'Product',offers:{'@type':'Offer',url:valid.source,priceCurrency:'AUD',price:1.7,...offer}})+'</script>';
assert.equal(pages.extractProduct(ld({}),valid.source).offer.price,1.7);
assert.equal(pages.extractProduct(ld({priceCurrency:'USD'}),valid.source),null);
assert.equal(pages.extractProduct(ld({url:'https://attacker.test/oats'}),valid.source),null);
assert.equal(pages.extractProduct('<script type="application/ld+json">broken</script>',valid.source),null);
const updated=await pages.readRetailerPage(valid,async()=>new Response(ld({price:'2.00'}),{headers:{'Content-Type':'text/html'}}));assert.equal(updated.price,2);assert.ok(Date.parse(updated.checked)>=Date.parse(valid.checked));assert.equal(updated.original,null);
await assert.rejects(()=>pages.readRetailerPage(valid,async()=>new Response('captcha',{headers:{'Content-Type':'text/html'}})),/No usable/);
await assert.rejects(()=>pages.readRetailerPage(valid,async()=>new Response('',{status:302,headers:{Location:'http://127.0.0.1'}})),/302/);
await assert.rejects(()=>pages.readRetailerPage(valid,async()=>new Response('x',{headers:{'Content-Type':'text/html','Content-Length':'3000000'}})),/size limit/);
globalThis.__adminTest={env:{SAVEHALF_ADMIN_EMAIL:'owner@example.test'},getChatGPTUser:async()=>({email:'viewer@example.test'})};
const adminSource=readFileSync('lib/admin.ts','utf8').replace(/^import .*;\n/gm,'');
const admin=await moduleFrom('const {env,getChatGPTUser}=globalThis.__adminTest;\n'+adminSource);assert.equal(await admin.isAdmin(),false);assert.equal(admin.sameOrigin(req({})),true);assert.equal(admin.sameOrigin(req({},'https://attacker.test')),false);
console.log('Passed: real observation validation, freshness, units, source allowlists, parser integrity, no-price failures, redirects, response bounds, favourite authentication/isolation, and owner/origin authorization.');
